server:
  port: 7777

logging:
  level:
    org:
      springframework:
        boot: INFO
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG

spring:
  profiles:
    active: memory
  flyway:
    enabled: false

invoicing-system:
  allowedOrigins: http://localhost:4200
  csrf:
    disable: true
