package pl.futurecollars.invoicing.model;

import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDate;
import java.util.List;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class Invoice {

  @Schema(description = "Invoice id (generated by app)", example = "1")
  private int id;

  @Schema(description = "Date invoice was created")
  private LocalDate date;

  @Schema(description = "Company who bought the product/service")
  private Company buyer;

  @Schema(description = "Company who is selling the product/service")
  private Company seller;

  @Schema(description = "List of products/services")
  private List<InvoiceEntry> entries;

  public Invoice(LocalDate date, Company buyer, Company seller, List<InvoiceEntry> entries) {
    this.date = date;
    this.buyer = buyer;
    this.seller = seller;
    this.entries = entries;
  }
}
